name: Wake up Streamlit App

on:
  schedule:
    # Chạy mỗi 15 phút một lần (Bạn có thể chỉnh lại)
    - cron: '*/15 * * * *'
  workflow_dispatch: # Cho phép bạn nhấn nút chạy thử thủ công

jobs:
  ping_app:
    runs-on: ubuntu-latest
    steps:
      - name: Send request to Streamlit
        run: |
          curl -s -L -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" https://fruit-visual-question-answering.streamlit.app/ --max-redirs 5
